name: ${project.name}
version: ${project.version}-${build.number}
main: me.minoneer.hopperlimit.HopperLimit
author: minoneer
description: ${project.description}
softdepend: [PlotMe]
commands:
  hopper:
    description: /hopper help for more information
    usage: /<command>
    permission: hopperlimit.count
