name: HopperLimit
version: '1.12'
main: me.minoneer.hopperlimit.HopperLimit
author: minoneer
description: Limits the hopper which can be placed in a defined area
softdepend: [PlotMe]
commands:
  hopper:
    description: /hopper help for more information
    usage: /<command>
    permission: hopperlimit.count